export enum SessionStatus {
  INCOMPLETE = 0,
  COMPLETED = 1
}

export enum SessionOutcome {
  PHOTOS_HAVE_BEEN_PROVIDED_TO_THE_PATRIOT = 0,
  PHOTOGRAPHER_HAS_NOT_PROVIDED_PHOTOS_YET = 1,
  PATRIOT_DID_NOT_SHOW_UP_FOR_APPOINTMENT = 2,
  NO_COMMUNICATION_UNABLE_TO_SCHEDULE = 3,
  OTHER = 4
}
